### ndarray.ndim
the number of axes (dimensions) of the array.

### ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

### ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape.

### ndarray.dtype
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

### ndarray.itemsize
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

### ndarray.data
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.size

15

In [8]:
a.dtype.name

'int32'

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([(1.5,2,3), (4,5,6)]) #注意圆括号，方括号
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
b.shape
# 除了最外层用圆括号，内存用方括号还是圆括号是随意的,只要匹配的对
# c,d (2*3*4)
c = np.array([
    [ [1, 1, 1, 1],       [1, 1, 1, 1],        [1, 1, 1, 1] ],
    [ [1, 1, 1, 1],       [1, 1, 1, 1],        [1, 1, 1, 1] ] 
] )

d = np.array([
    [ (1, 1, 1, 1),        (1, 1, 1, 1),        (1, 1, 1, 1) ],

       [(1, 1, 1, 1),        (1, 1, 1, 1),        (1, 1, 1, 1) ] 
       
] )

In [12]:
d.ndim

3

In [13]:
 np.arange( 0, 2, 0.2 )              # it accepts float arguments

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [14]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [15]:
x = np.linspace( 0, 2*np.pi, 100 )
f = np.sin(x)

In [16]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [17]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a-b
d=b**2
e= 10*np.sin(a)
f=a<35  #array([ True, True, False, False])


In [18]:
f

array([ True,  True, False, False])

In [22]:
b = np.arange(1.5)
b

array([0., 1.])

In [24]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
C = A * B # 元素相乘
D= A @ B #矩阵内积  等同于 np.dot(A,B)
#   *=  +=  等都可以用
print(C)

[[2 0]
 [0 4]]


In [25]:
D

array([[5, 4],
       [3, 4]])